// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1:string):Promise<boolean>;

export function FileExists():Promise<boolean>;

export function GetDataPath():Promise<string>;

export function GetItem(arg1:string):Promise<string>;

export function IsEncrypted():Promise<boolean>;

export function Login(arg1:string):Promise<boolean>;

export function MoveFile():Promise<string>;

export function RemoveItem(arg1:string):Promise<boolean>;

export function SetItem(arg1:string,arg2:string):Promise<boolean>;
