// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function FileExists() {
  return window['go']['main']['App']['FileExists']();
}

export function GetDataPath() {
  return window['go']['main']['App']['GetDataPath']();
}

export function GetItem(arg1) {
  return window['go']['main']['App']['GetItem'](arg1);
}

export function IsEncrypted() {
  return window['go']['main']['App']['IsEncrypted']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function MoveFile() {
  return window['go']['main']['App']['MoveFile']();
}

export function RemoveItem(arg1) {
  return window['go']['main']['App']['RemoveItem'](arg1);
}

export function SetItem(arg1, arg2) {
  return window['go']['main']['App']['SetItem'](arg1, arg2);
}
